name: Set up scaffold

on:
  push:
    branches: ['main']

jobs:
  set-up:
    if: ${{ github.run_number == 1 && github.repository != 'compulim/template-vscode-extension' }}
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Configure user profile
        run: |
          git config user.email "${{ format('@{0}', github.actor) }}"
          git config user.name "${{ format('@{0}', github.actor) }}"
      - name: Run Yeoman
        run: npx --package=yo --package=generator-code -- yo code . -t=ts -q
      - name: Update package.json
        run: |
          npm version --no-git-tag-version 0.0.0-0
          cat package.json | jq '.repository.type = "git"' | jq '.repository.url = "${{ github.repositoryUrl }}"' | jq '.homepage = "https://github.com/${{ github.repository }}#readme"' > package-temp.json && mv package-temp.json package.json
      - name: Commit and push
        run: |
          rm ./.github/workflows/set-up-scaffold.yml
          git add --all
          git commit --message "Initial 'template-vscode-extension' scaffold"
          git push --set-upstream origin ${{ github.event.inputs.target-branch }}
